<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{720f5241-2610-4e42-b247-84b15ca27248}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i: INT;
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[ PLC_PRG();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>